spring:
  profiles:
    active: local

server:
  port: 8081
#  use-forward-headers: true

keycloak:
  #enabled: false
  realm: demo
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: home-manager
  #  verify-token-audience: true
  credentials:
    secret: 3347a9f6-c38b-4317-b8f2-813f8f248951
  use-resource-role-mappings: true # jwt 안의 resource_access 에 role 을 본다, 기본은 realm_access의 role을 본다.
  bearer-only: true
  #  confidential-port: 443
  securityConstraints[0]:
    securityCollections[0]:
      name: public endpoints
      patterns[0]: /home
  securityConstraints[1]:
    authRoles[0]: user
    securityCollections[0]:
      name: protected endpoints
      patterns[0]:  /test/*

# local
---
spring.profiles: local
spring.profiles.include: hsqldb-file

# test
---
spring.profiles: test
spring.profiles.include: hsqldb-mem

# development
---
spring.profiles: development
spring.profiles.include: testdb

# production
---
spring.profiles: production
spring.profiles.include: testdb


# datasource - testdb
---
spring.profiles: testdb
spring.profiles.include: sql-debug
spring:
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/geokkurodb?useUnicode=yes&characterEncoding=UTF-8
    username: geokkuro
    password: geokkuro1234

# datasource - hsqldb
---
spring.profiles: hsqldb
spring.profiles.include: sql-debug
spring:
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.HSQLDialect
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:


---
spring.profiles: hsqldb-file
spring.profiles.include: hsqldb

spring:
  datasource:
    url: jdbc:hsqldb:file:./hsqldb/homemanager;sql.syntax_mys=true;

---
spring.profiles: hsqldb-mem
spring.profiles.include: hsqldb

spring:
  datasource:
    url: jdbc:hsqldb:mem:homemanager;sql.syntax_mys=true;


---
spring.profiles: sql-debug
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE





