CREATE TABLE `USERS` (
 ID INT NOT NULL AUTO_INCREMENT,
 USER_ID VARCHAR(255) NOT NULL,
 MRN VARCHAR(255) NOT NULL,
 EMAIL VARCHAR(255),
 PERMISSIONS VARCHAR(4000),
 FIRST_NAME VARCHAR(255),
 LAST_NAME VARCHAR(255),
 PASSWORD VARCHAR(255),
 CREATE_DATE DATETIME,
 UPDATE_DATE DATETIME,
  PRIMARY KEY ( ID),
  UNIQUE (USER_ID),
  UNIQUE (MRN),
);

